### ISSUE TITLE
Android Fused Location Provider api

### ISSUE THREAD

**Issue by msimonc** [christocracy/cordova-plugin-background-geolocation#136]
Chris, is there any reason why, AFAIK, you don't use Android's Fused Location Provider?  Thanks

**Comment by christocracy** [comment]
Good question.  I recall reading about it while I was in the Android depths
last year.  Let me know if you have any suggestions.  Android certainly
needs help in the battery-consumption dept.


On Mon, Jan 26, 2015 at 5:37 PM, Mark Simon <notifications@github.com>
wrote:

> Chrisk, is there any reason why you, AFAIK, don't use Android's Fused
> Location Provider? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/136>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>

**Comment by msimonc** [comment]
Crazy talk:  have you ever considered doing that coding in a paid version of the plugin?

**Comment by christocracy** [comment]
Good idea.  Bad news for the Phonegap build folks, which I don't use :)

On Tuesday, January 27, 2015, Mark Simon <notifications@github.com> wrote:

> Crazy talk: have you ever considered doing that coding in a paid version
> of the plugin?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/136#issuecomment-71744701>
> .
>


-- 
Snet from Gmail Mobile

**Comment by christocracy** [comment]
Ok, I've got [FusedLocationProviderApi](https://developer.android.com/reference/com/google/android/gms/location/FusedLocationProviderApi.html) working, as well as [ActivityRecognitionApi](https://developer.android.com/reference/com/google/android/gms/location/ActivityRecognitionApi.html).  Works really well!  This will be a significant improvement in battery performance since ```ActivityRecognitionApi``` uses accelerometer / gyroscope to detect significant movement ```(ON_FOOT, ON_BICYCLE, IN_VEHICLE, STILL)``` rather than the current method which runs a timer and samples the GPS ever 2 min, all day and all night.

I'm thinking of putting it into a private repo and charging $500.

**Comment by msimonc** [comment]
That's excellent.  It's going to be a hit with projects where background location is a long lived activity that triggers, for example, notifications that when opened will bring the app to the foreground.
