### ISSUE TITLE
Price

### ISSUE THREAD

**Issue by anaibol** [christocracy/cordova-plugin-background-geolocation#167]
Hi, I would really like to buy the premium version, but it's very expensive for me. I live in Argentina, and 500 usd it's a lot of money here. I think I would buy it for 50 usd. Could you consider it?

Thanks!

**Comment by christocracy** [comment]
Sorry, no.  I’m making a lot of sales so I have no downward
price-pressure.  I’m actually considering doubling the price to $1000 to
cool down sales (since I have to support everybody).

I’d rather cut my sales in half to support half the people.

On Fri, Apr 17, 2015 at 10:42 AM, Juan Anibal Micheli <
notifications@github.com> wrote:

> Hi, I would really like to buy the premium version, but it's very
> expensive for me. I live in Argentina, and 500 usd it's a lot of money
> here. I think I would buy it for 50 usd. Could you consider it?
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/christocracy/cordova-plugin-background-geolocation/issues/167>
> .
>



-- 
Chris Scott
Transistor Software <http://www.transistorsoft.com>
