### ISSUE TITLE
Memory Consumption

### ISSUE THREAD

**Issue by pmwisdom** [christocracy/cordova-plugin-background-geolocation#183]
I profiled an iphone 4s while in the background. This only happens with the BG plugin enabled, and if I stop, it will level out, but not collect its garbage. Note that at t = 1 minute the app was sitting at ~100 megs. It will rise until iOS force closes the app because of repeated memory warnings.  

Note that I was simulating extremely aggressive location tracking. So This may not be a memory leak persay. Just high memory consumption.

![Xcode Profile](http://www.sumoware.com/images/temp/xzqdadfaffklesjh.png)

Edit: I did some optimizations and it stops around 240 megs.

**Comment by christocracy** [comment]
In the [Premium version](http://christocracy.github.io/cordova-background-geolocation/), I've decoupled the core location code into a Framework and used it in a pure native Sample App.

### Running in a pure native app
![Pure Native](https://www.dropbox.com/s/7hsit5mtx7hp4tj/Screenshot%202015-05-15%2010.29.04.png?dl=0)

Flat-lined at 103MB.

### Running in Cordova SampleApp from repo
![Cordova SampleApp](https://www.dropbox.com/s/e9e1jh5uyo1ollm/Screenshot%202015-05-15%2010.29.42.png?dl=0)

**Note:** When analyzing memory consumption, you'll want to set ```debug: false``` since the plugin is very verbose with logging.

**Comment by pmwisdom** [comment]
Ah I didn't realize it was doing SQLite persistence (in case of connectivity issues?).

Its really not a problem on phones newer than a 4s, and apps that are small, but I just thought Id bring if to your attention if you hadn't seen that. 

Thanks for the thorough answer.

**Comment by christocracy** [comment]
Yes, both iOS & Android persist each location and delete once synced to your server.  Since I plan to implement the core location code into a number of other frameworks beyond Cordova (eg React Native or pure native apps), it makes sense to carry a persistence & HTTP layers within the plugin rather than having to reimplement those layers for each platform.
