### ISSUE TITLE
Moving Geofencing points

### ISSUE THREAD

**Issue by lakano** [christocracy/cordova-plugin-background-geolocation#207]
Hello,

In your premium version, you speak about native geofencing.
If I understood, this permit to open our app when the device is inside a circular geofence.

1) Do this works even if the app is not opened ?

2) There is a solution to change the geofences to watch in background mode ?
Because the geofence to watch is another phone device, and so the geolocation change everytime. 

So, inside the yourAjaxCallback function (when your plugin submit my geolocation to my server), my server could add in the response, the list of geofences to watch, then we could change it in theory ?
But do this works only in foreground ?

Regards,

**Comment by christocracy** [comment]
Have you tried the [Sample App](https://github.com/christocracy/cordova-background-geolocation-SampleApp)?

1. Do this works even if the app is not opened ?

From [Apple Documentation](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/index.html#//apple_ref/doc/uid/TP40007125-CH3-SW32)

> "In iOS, the regions you register with the location manager persist between launches of your 
> application. If a region crossing occurs while your iOS app is not running, the system automatically 
> wakes it up (or relaunches it) in the background so that it can process the event. When relaunched, all 
> of the regions you configured previously are made available in the monitoredRegions property of any 
> location manager objects you create."

2. There is a solution to change the geofences to watch in background mode ?
Because the geofence to watch is another phone device, and so the geolocation change everytime.

You simply re-create the geofence each time the target device reports a new location.  A geofence created with the same identifier as an existing one will overwrite the previous.

```
  bgGeo.addGeofence({identifier: "target-phone", notifyOnEntry: true, latitude: 1, longitude: 1});
  .
  .
  .
  bgGeo.addGeofence({identifier: "target-phone", notifyOnEntry: true, latitude: 2, longitude: 2});
  .
  .
  .
  bgGeo.addGeofence({identifier: "target-phone", notifyOnEntry: true, latitude: 3, longitude: 3});
  .
  .
  .
```

**Comment by lakano** [comment]
Thanks !
